#!/bin/bash

###################
## BUILD AND RUN ##
###################

# Note this depends on having NASM installed. (sudo apt install nasm)

# How to use:
# Pass this script an 8086 .nasm assembly file.
# This script will use NASM to assemble it. If
# the .asm is sufficiently simple (and if we're
# a little lucky), the assembly program assembled
# with NASM will be simulated, with debug logs.

clear

#Delete all output files from previous runs.
mkdir -p output
rm output/*

#C source file name, sans extension
simulator_name="sim8086"
#asmIN is the .asm passed to this script as an argument
asmIN=$1

echo "[[[ASSEMBLE ARGUMENT .ASM FILE WITH NASM...]]]"
#[output file 1] NASM assembles argument .asm to .bin
nasm $asmIN -o output/1_nasm_assembled.bin

echo "[[[COMPILE 8086 SIMULATOR WITH GCC...]]]"
#Compile the simulator
gcc $simulator_name.c -Wall -Werror -std=c99 -o output/$simulator_name.bin 

echo "[[[RUN NASM OUTPUT WITH SIMULATOR...]]]"
#[output file 2] Disassemble (Params are input bin, output asm)
./output/$simulator_name.bin output/1_nasm_assembled.bin output/2_simulator.disasm

echo "[[[DONE]]]"

#END
