#!/bin/bash

###################
## BUILD AND RUN ##
###################

# This assembles a .asm file with NASM,
# builds the disassembler from C source,
# uses it to disassemble the NASM output,
# and finally tests output by diffing bins.
# Needs a .asm file as an argument.

echo "Argument 1 for bar is: "
echo $1
echo " "

#C source file name, sans extension
disassembler_name="disasm8086"
#inASM is the .asm passed to this .bat as an argument
inASM=$1

#[1] NASM assembles argument .asm to .bin
nasm $inASM -o output/1_nasm_assembled.bin

#Compile the disassembler
gcc $disassembler_name.c -o $disassembler_name.bin
#[2] Disassemble (Params are input bin, output asm)
./$disassembler_name.bin output/1_nasm_assembled.bin output/2_disasm8086.disasm

echo .
echo [Re-assembling for binary comparison...]
echo .

#[3] NASM RE-assembles our .disasm code
nasm output/2_disasm8086.disasm -o output/3_nasm_REassembled.bin

#Compare
echo /\\Comparing original bin with re-assembled bin...
diff output/1_nasm_assembled.bin output/3_nasm_REassembled.bin
echo \\/Comparison over.

#Clean up output
echo .
echo Cleaning up output files...
mv output/* output_old
echo .
echo done

#END
